### ISSUE TITLE
Add simulation of amorphous sample

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift-usim#12]
From Scanning Transmission Electron Microscopy book (p125): "sample function for an amorphous sample by generating a random phase and applying a Gaussian filter to the Fourier transform".

Andreas additional comment: "complex data with random imaginary part and 0 real part, Gaussian, IFFT"

**Comment by Brow71189** [comment]
These images were created with the following code:
![Figure_1](https://user-images.githubusercontent.com/16721195/57492321-45d77900-7275-11e9-84e4-fe2fd109598a.png)

```
import numpy as np
from scipy.ndimage import gaussian_filter, fourier_gaussian
import matplotlib.pyplot as plt
random_data = np.random.rand(512, 512)*2-1
real_space = gaussian_filter(random_data, 3)
random_phase = np.fft.ifft2(fourier_gaussian(random_data*1j, 3)).real
fig, ax = plt.subplots(1, 2, figsize=(8, 4))
ax[0].matshow(real_space)
ax[0].set_title('real space')
ax[0].axis('off')
ax[1].matshow(random_phase)
ax[1].set_title('random phase')
ax[1].axis('off')
plt.show()
```

**Comment by Brow71189** [comment]
Couldn't that be closed since we have the amorphous sample?
