### ISSUE TITLE
Control fields in InstrumentPanel are empty

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift-usim#37]
<img width="273" alt="Unbenannt" src="https://user-images.githubusercontent.com/16721195/157213159-3219dbf5-cb54-4124-a2d8-ec86bbbce4d9.PNG">

**Comment by cmeyer** [comment]
Thanks. I introduced this bug when changing the callbacks to not retain references to self in 6e9caec7b74992dcc2caa8f52ce5edb3f5b338a3.
